cache:
  mount:
    - node_modules

build:
  image: reddit/reddit-nodejs:latest
  pull: true
  commands:
    - apt-get update
    - apt-get install build-essential
    - git submodule init
    - git submodule update
    - npm install
    - npm run lint
    - npm run test
    - npm run build

publish:
  docker:
    username: $$DOCKERHUB_USERNAME
    password: $$DOCKERHUB_PASSWORD
    email: sysops@reddit.com
    repo: reddit/reddit-mobile
    tag: $$BRANCH
    file: Dockerfile.staging

notify:
  slack:
    webhook_url: $$CI_SLACK_WEBHOOK_URL
    channel: ci-notifications
  slack:
    webhook_url: $$CI_SLACK_WEBHOOK_URL
    repo: reddit/reddit-mobile
    channel: frontend-platform
